baseURL = "https://econ-archive.netlify.app/"
languageCode = "ko-kr"
title = "경제학 아카이브"
theme = "xmin"

[params]
  description = "수험생을 위한 경제학 기출문제 정리"
  author = "Geunyeong"
  math = true  # KaTeX 수식 렌더링

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag      = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  section = ["HTML", "RSS", "SITEMAP"]
  page = ["HTML", "SITEMAP"]

[frontmatter]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/general"
  [frontmatter.defaults.values]
  categories = ["일반행정"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/finance"
  [frontmatter.defaults.values]
  categories = ["재경"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/diplomat"
  [frontmatter.defaults.values]
  categories = ["외교관후보자"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/legislative"
  [frontmatter.defaults.values]
  categories = ["입법고시"]

