baseURL = "https://econ-archive.netlify.app/"
languageCode = "ko-kr"
theme = "xmin"
title = "5급 경제학 기출문제 아카이브"

[params]
  description = "5급 공무원 경제학 기출문제를 연도별로 정리한 아카이브 사이트입니다. 일반행정, 외교원, 입법고시 등 수험생을 위한 자료 제공."
  author = "Geunyeong"
  math = true  # KaTeX 수식 렌더링

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag      = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    name = "전체"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "시험별"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "키워드"
    url = "/tags/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "SITEMAP", "JSON"]
  section = ["HTML", "RSS", "SITEMAP"]
  page = ["HTML", "SITEMAP"]

[frontmatter]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/general"
  [frontmatter.defaults.values]
  categories = ["일반행정"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/finance"
  [frontmatter.defaults.values]
  categories = ["재경"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/diplomat"
  [frontmatter.defaults.values]
  categories = ["외교관후보자"]

[[frontmatter.defaults]]
  [frontmatter.defaults.scope]
  path = "post/legislative"
  [frontmatter.defaults.values]
  categories = ["입법고시"]

